[build]
# uncommented when checking wasm code on correctnes and reload rust-analyzer
# target = "wasm32-unknown-unknown"

# only works if cargo install wasm-bindgen-cli --vers "X.Y.Z"
# where "X.Y.Z" => currently used (see Cargo.toml) wasm_bindgen version
[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
