/// traits for event emitting in the host code (feat: `tauri`)
#[cfg(any(not(target_family = "wasm"), feature = "tauri"))]
pub mod emit;
/// related generic struct and functions for autogenerated listen functions (target: `wasm` or feat: `wasm`)
#[cfg(any(target_family = "wasm", feature = "wasm"))]
pub mod listen;
