#![warn(missing_docs)]
#![doc = include_str!("../README.md")]

/// wasm bindings for tauri's provided js functions
#[cfg(any(target_family = "wasm", feature = "wasm"))]
pub mod bindings;
/// wrapped bindings for easier use in the generated wasm commands
#[cfg(any(target_family = "wasm", feature = "wasm"))]
pub mod command;
/// related generic struct and functions for autogenerated listen functions
#[cfg(all(any(target_family = "wasm", feature = "wasm"), feature = "listen"))]
pub mod listen;

pub use tauri_interop_macro::*;
