#![warn(missing_docs)]
#![doc = include_str!("../README.md")]

/// wasm bindings for tauri's provided js functions (target: `wasm` or feat: `wasm`)
#[cfg(any(target_family = "wasm", feature = "wasm"))]
pub mod bindings;
/// wrapped bindings for easier use in the generated wasm commands (target: `wasm` or feat: `wasm`)
#[cfg(any(target_family = "wasm", feature = "wasm"))]
pub mod command;
/// traits for event emitting in the host code (feat: `event` and feat: `tauri`)
#[cfg(all(not(target_family = "wasm"), feature = "event", feature = "tauri"))]
pub mod emit;
/// related generic struct and functions for autogenerated listen functions (target: `wasm` or feat: `wasm` and feat: `event`)
#[cfg(all(any(target_family = "wasm", feature = "wasm"), feature = "event"))]
pub mod listen;

pub use tauri_interop_macro::*;
