name: Rust

on:
  push:
    branches: [dev, main]
    paths:
      [
        "**.rs",
        "Cargo.toml",
        "Cargo.lock",
        "rustfmt.toml",
        ".github/workflows/*",
        "!*.md",
        "!contrib/*",
        "!docs/*",
        "!LICENSE",
        "!*.sh",
      ]
  pull_request:
    paths:
      [
        "**.rs",
        "Cargo.toml",
        "Cargo.lock",
        "rustfmt.toml",
        ".github/workflows/*",
        "!*.md",
        "!contrib/*",
        "!docs/*",
        "!LICENSE",
        "!*.sh",
      ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

    - name: install dependencies (ubuntu only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1 libayatana-appindicator3-dev

    - name: Run tests for crate
      run: |
        cd tauri-interop-macro
        cargo test --features event,leptos,initial_value

    - name: Run tests for crate (no features)
      run: cargo test --features=event

    - name: Run tests for crate (all-features)
      run: cargo test --all-features

    - name: Build test-project (wasm)
      run: |
        cd test-project
        cargo build --target wasm32-unknown-unknown

    - name: Build test-project (host)
      run: |
        cd test-project/api
        cargo build --target x86_64-unknown-linux-gnu
